FROM nginx:alpine

# Copier la configuration Nginx
COPY default.conf /etc/nginx/conf.d/default.conf

# Copier les fichiers statiques
COPY src/main/resources/static /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g","daemon off;"]