# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/moviedb
spring.datasource.username=postgres
spring.datasource.password=oumaymazekri09092001@
spring.datasource.driver-class-name=org.postgresql.Driver


# Initialisation des données
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Configuration Redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=60000
spring.cache.redis.cache-null-values=false


# Configuration du serveur
server.port=8080

# Configuration Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Informations sur l'application
info.app.name=Movie Management API
info.app.description=Application de gestion de films
info.app.version=1.0.0

# Configuration Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method


# Configuration JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


